default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: instagram_clone_backend
  port: 5432

development:
  <<: *default
  database: instagram_clone_backend_development
  password: P4$$v0rd
  host: localhost

test:
  <<: *default
  database: instagram_clone_backend_test
  password: P4$$v0rd

production:
  <<: *default
  database: instagram_clone_backend_production
  username: instagram_clone_backend
  password: <%= ENV['DEVISE_JWT_SECRET_KEY'] %>
